services:
  # PostgreSQL Database
  - type: pserv
    name: daily-register-db
    env: docker
    plan: free
    region: oregon
    ipAllowList: []

  # Web Service
  - type: web
    name: daily-register-app
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: daily-register-db
          property: connectionString
    healthCheckPath: /api/health
